name: notion

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  import:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - id: import
        uses: ega4432/notion-to-markdown-action@v0
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: '619787c75b60479886c147cf746bfbb8'
        with:
          # Optional
          output_path: content # default: output
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
